// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://klgwyydsyinmirmttcfe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtsZ3d5eWRzeWlubWlybXR0Y2ZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwMzIyNDEsImV4cCI6MjA1ODYwODI0MX0.OUbJ5Ri2rM4wRIJeEALCb8uxr9jqlmFqV6XS3X-qyK0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);